name: Build and Deploy VuePress to GitHub Pages

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
  workflow_dispatch: # 允许手动触发此工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read # 只读访问仓库内容
      pages: write # 写入权限以更新 GitHub Pages
      id-token: write # 如果需要 OIDC token (通常不需要)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true # 如果你的项目依赖于子模块，请设置为 true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16" # 使用 VuePress 支持的 Node 版本，这里选择 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build VuePress site
        run: npm run docs:build # 根据你的 package.json 中定义的脚本调整

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vuepress/dist # 构建输出目录，请根据实际情况修改
          force_orphan: true # 确保每次部署都是干净的状态
